import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of service for Sternes.dev',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <article className="prose prose-slate lg:prose-lg max-w-none">
          <h1 className="text-4xl font-bold mb-8" style={{ fontFamily: 'var(--font-display)' }}>
            Terms of Service
          </h1>

          <p className="text-gray-600 mb-8">
            Last updated: March 30, 2026
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Agreement to Terms
            </h2>
            <p>
              By accessing or using Sternes.dev (the "Website"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these Terms, you may not access the Website.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Description of Services
            </h2>
            <p>
              Sternes.dev provides information about full-stack engineering and AI integration services, including but not limited to:
            </p>
            <ul>
              <li>Web development and application development services</li>
              <li>AI workflow integration and consultation</li>
              <li>E-commerce solutions</li>
              <li>Content management system implementation</li>
              <li>AI-powered client fit assessment tools</li>
            </ul>
            <p>
              The Website also provides an AI-powered tool to help potential clients assess whether their project is a good fit for our services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Use of AI Assessment Tool
            </h2>
            <p>
              Our AI-powered fit assessment tool uses Anthropic's Claude API to analyze project descriptions and provide preliminary assessments. By using this tool, you acknowledge that:
            </p>
            <ul>
              <li>The assessment is for informational purposes only and does not constitute a binding commitment or contract</li>
              <li>The assessment is generated by AI and may not be completely accurate</li>
              <li>Your input will be processed by third-party AI services (Anthropic)</li>
              <li>You will not submit sensitive, confidential, or proprietary information through the assessment tool</li>
              <li>Rate limits apply to prevent abuse (5 requests per hour per IP address)</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Intellectual Property
            </h2>
            <p>
              The Website and its original content, features, and functionality are owned by Rashad Sternes and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
            </p>
            <p>
              You may not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Website without prior written consent, except for your own personal, non-commercial use.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              User Conduct
            </h2>
            <p>
              You agree not to:
            </p>
            <ul>
              <li>Use the Website for any unlawful purpose or in violation of these Terms</li>
              <li>Attempt to gain unauthorized access to any portion of the Website or any systems or networks</li>
              <li>Use any automated system, including "robots," "spiders," or "scrapers" to access the Website</li>
              <li>Circumvent, disable, or interfere with security-related features or rate limiting</li>
              <li>Transmit any viruses, worms, defects, Trojan horses, or other destructive items</li>
              <li>Use the Website to send spam or unsolicited messages</li>
              <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Third-Party Links and Services
            </h2>
            <p>
              The Website may contain links to third-party websites or services (such as Calendly and Anthropic) that are not owned or controlled by Sternes.dev. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Disclaimers
            </h2>
            <p>
              THE WEBSITE AND ALL INFORMATION, CONTENT, MATERIALS, AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE WEBSITE ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.
            </p>
            <p>
              WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p>
              WE DO NOT WARRANT THAT:
            </p>
            <ul>
              <li>The Website will be available at any particular time or location, uninterrupted or secure</li>
              <li>Any defects or errors will be corrected</li>
              <li>The Website is free of viruses or other harmful components</li>
              <li>The results of using the Website will meet your requirements</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Limitation of Liability
            </h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL RASHAD STERNES OR STERNES.DEV BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE WEBSITE.
            </p>
            <p>
              OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATING TO THE WEBSITE SHALL NOT EXCEED $100.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Indemnification
            </h2>
            <p>
              You agree to indemnify, defend, and hold harmless Rashad Sternes, Sternes.dev, and their affiliates from and against all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from your use of the Website or violation of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Governing Law and Jurisdiction
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Texas, United States, without regard to its conflict of law provisions.
            </p>
            <p>
              Any disputes arising from these Terms or your use of the Website shall be resolved exclusively in the state or federal courts located in Dallas County, Texas.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Changes to Terms
            </h2>
            <p>
              We reserve the right to modify or replace these Terms at any time at our sole discretion. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect.
            </p>
            <p>
              By continuing to access or use the Website after revisions become effective, you agree to be bound by the revised Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Severability
            </h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4" style={{ fontFamily: 'var(--font-display)' }}>
              Contact Information
            </h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-4">
              Email: <a href="mailto:hello@sternes.dev" className="text-blue-600 hover:underline">hello@sternes.dev</a>
            </p>
          </section>

          <div className="mt-12 pt-8 border-t border-gray-200">
            <a href="/" className="text-blue-600 hover:underline">
              ← Back to Home
            </a>
          </div>
        </article>
      </div>
    </main>
  )
}
